name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: turkenh/uptest/.github/workflows/pr-comment-trigger.yml@main
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_AWS_CREDS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_EXAMPLE_VALUE_REPLACEMENTS }}
